### ISSUE TITLE
Model Caching

### ISSUE THREAD

**Issue by abunet** [Grinderofl/FluentModelBuilder#9]
Hi, 
is there a way to avoid caching of model with FluentModelBuilder?
I have a database with multiple tables, all with the same structure. each table naem has a different prefix.
CREATE TABLE X000001Log([Id] [int] NOT NULL, [Date] [datetime] NOT NULL)
CREATE TABLE X000002Log([Id] [int] NOT NULL, [Date] [datetime] NOT NULL)
CREATE TABLE X000003Log([Id] [int] NOT NULL, [Date] [datetime] NOT NULL)

In an ASP .NET 5 application the model is cached the first time it has been built.
The OnModelCreating is fired only once time for the entire life cicle of the app

```
        private string _prefix;
        private bool _rebuildModel;

        public MyContext(string prefix, bool rebuildModel) {

            _prefix = prefix;
            _rebuildModel = rebuildModel;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            options.UseSqlServer(@"Server=(local);Database=mydb;Trusted_Connection=True;");

            if (_rebuildModel)  {
                 /* what can i do here? */
            }
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<LOG>().ToTable(string.Concat(_prefix, "log"));

```

Any suggestion?
Thanks in advance

**Comment by Grinderofl** [comment]
@abunet If you need to dynamically rebuild your model during runtime, you'll need to either:

a) Initiate your model manually, like this:

``` c#
if (_rebuildModel) {
    var builder = new ModelBuilder(new CoreConventionSetBuilder().CreateConventionSet());
    OnModelCreating(builder);
    options.UseModel(builder.Model)
}
```

b) Subclass `ModelCacheKey` and `ModelCacheKeyFactory` and override Create method of `SubclassedModelCacheKeyFactory`, returning your own `SubclassedModelCacheKey` based on the value of `prefix` which should be injected and decided via a service. The `SubclassedModelCacheKey` would then become invalidated as the prefix changes, and the model is regenerated. You will also need to replace the default `ModelCacheKeyFactory` in your services:

``` c#
services.Replace(ServiceDescriptor.Singleton<IModelCacheKeyFactory, SubclassedModelCacheKeyFactory>());
```

Might want to hold off using FluentModelBuilder for now, I haven't updated it to EntityFrameworkCore yet, it'll be using a slightly different mechanic to override the modelbuilder (although it won't change what you'd need to do for this specific task).

**Comment by abunet** [comment]
Best 3 lines of code found on EF7 all over the web !!
For now , I opted for the solution A, although also overwrite the ModelCacheKeyFactory is more elegant . Thanks again.

**Comment by LucaGabi** [comment]
Can you help update to EF Core 2.1 ?

Thanks.

**Comment by Diaskhan** [comment]
))

**Comment by Diaskhan** [comment]
There might been problem !
There is not enogh inmormation to understand dbcontext relations to another dependencies to another classes ! 
There misunderstood about architecture of Yore orm  !
